name: salad_da
description: Online salad market

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

# BSD
  firebase_auth: ^1.0.1
  firebase_core: ^1.0.1
  firebase_storage: ^8.0.0
  cloud_firestore: ^1.0.1
  http: ^0.13.0
  provider: ^5.0.0
  url_launcher: ^6.0.2
  google_sign_in: ^5.0.1
  sign_in_with_apple: ^3.0.0
  crypto: ^3.0.0
  intl: ^0.17.0
  image_cropper: ^1.3.1

# Apache 2.0
  image_picker: ^0.7.3

# MIT License
  carousel_slider: ^3.0.0
  get: ^3.26.0
  cached_network_image: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/fonts/
    - assets/images/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Recursive
      fonts:
        - asset: assets/fonts/Recursive.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto.ttf

  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
